  Introduction : 'GAN-free methods for gradient inversion attack.'
  
  optim : 'GAN_free'    #optim method, ['GAN_based', 'GAN_free']
  cost_fn : 'sim_cmpr0'   #the type of loss function 
  set_seed :       # random seed. Following geiping et. al., we do not give random seed for GAN-free methods.
  indices : 'def'      #decide which part of gradients to be involved in the final gradients match loss.
  weights : 'equal'    #weight of every graident scalar's matching loss
  init : 'randn'     #how we initial the original latent code.
  model : 'ResNet18'   #FL model
  restarts : 4

  num_images : 1   # the number of images to reconstruct at a batch
  num_exp : 10     # the number of experiments
  target_id : 10
  lr : 0.1            #learning rate for Yin et al.
  total_variation : 0.0001     #the coefficient of total variation 
  image_norm : 0.000001    #the coefficient of norm regularizer for Yin et al.
  group_lazy : 0.01    #choose if we use group lazy regularization for Yin et al.
  
  bn_stat : 0       #choose if we use bn statistic to regularizer 

  max_iterations : 1000    #Maximum number of iterations for reconstruction.

  gias_lr : 0.00001   #For biggan, we'd better choose smaller learning rate. 

  # For input data
  generative_model : ''
  gen_dataset : 'ImageNet64'    # ['ImageNet64', 'FFHQ64']
  dataset : 'MM_IMDB'       
  data_path : '/home/ubuntu/mnt-disk/data/mmimdb_custom/multimodal_dataset_128_115_100_25.hdf5'  # specify your dataset path

  #For output data
  exp_name : 'ex4_gan_free_mm_imdb'   #Same latent space search
  output_dir : '/home/ubuntu/mnt-disk/results/censor/mm_imdb'

  #Choice for GAN-free methods
  geiping : true
  yin : false

  train_epochs: 12
  our_num_tries : 20
  #Defense parameter
  defense_method : 'orthogonal'
  defense_setting : 
      noise : 0.01
      clipping : None
      compression : None
      representation : None
      orthogonal : null


  # The pre-trained StyleGAN checkpoint
  ckpt: None

  #LR pace for training
  lr_same_pace: false 
  
  # Multimodal
  is_multimodal : false
  # location of img in MM tensor
  image_tensor_dim_h : 128
  image_tensor_dim_w : 80
  